site_name: "Optakt Documentation"
copyright: "Copyright &copy; 2021 Optakt"
docs_dir: 'content'

nav:
  - 'Overview': 'index.md'
  - 'Code':
    - 'Design': 'code/design.md'
    - 'Go': 'code/go.md'
    - 'Markdown': 'code/markdown.md'
    - 'Testing': 'code/testing.md'
  - 'Process':
    - 'Meetings': 'process/process.md'
    - 'Repositories': 'process/repositories.md'
    - 'Git': 'process/git.md'
  - 'Knowledge':
    - 'Flow': 'knowledge/flow.md'
    - 'Cadence': 'knowledge/cadence.md'
    - 'Flare': 'knowledge/flare.md'
    - 'History Of Scaling in Blockchain': 'knowledge/scalinghistory.md'
    - 'Glossary': 'knowledge/glossary.md'

theme:
  name: material
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: white
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: indigo
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/wide.css

plugins:
  - markdownextradata
  - search
  - exclude:
      glob:
        - include/*.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - markdown_include.include:
      base_path: content/include/
      encoding: utf-8
